language: ruby
#dist: trusty
#before_install:
#  - gem install bundler && bundler -v
#  # setup mysql && make sure webp-ffi has all the dependencies
#  - sudo apt-get update
#  - sudo apt-get -y install mysql-server libjpeg-dev libpng-dev libtiff-dev libwebp-dev
rvm:
  - 2.2.4

